source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HGImagePicker_Example', :exclusive => true do
  pod "HGImagePicker", :path => "../"
end

target 'HGImagePicker_Tests', :exclusive => true do
  pod "HGImagePicker", :path => "../"

  
end
