source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

pod 'ClusterPrePermissions', '~> 0.1'
pod 'KASlideShow', '~> 2.2'

pod 'HGImagePicker', :git => 'https://github.com/sadiq81/HGImagePicker.git'